log:
  level: "info"
  format: "json"

storage:
  type: "postgres"
  postgres:
    host: "${POSTGRES_HOST}"
    port: ${POSTGRES_PORT}
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    dbname: "${DB_NAME}"
    sslmode: "disable"
  redis:
    addr: "${REDIS_ADDR}"
    password: "${REDIS_PASSWORD}"
    db: 0

services:
  gateway:
    port: 8080
  analytics:
    port: 8081
  evaluator:
    port: 8082
  management:
    port: 8083
  streamer:
    port: 8084
